### ISSUE TITLE
Incorrect copy on watch

### ISSUE THREAD

**Issue by zont** [AndyOGo/node-sync-glob#17]
Have folders:
```
src
     - config.json
     - index.html
out
```

Run:
```
sync-glob -w src/**/*.{html,json} out


DELETE out
COPY src\config.json to out\config.json
COPY src\index.html to out\index.html
WATCHING src/**/*.{html,json}
```

Try edit config.json and save:
```
COPY src\config.json to out\src\config.json
```
File writed to incorrect path

Should be the same is initial COPY:
```
COPY src\config.json to out\config.json
```

**Comment by AndyOGo** [comment]
@zont 
Thank you for your report.
I will firstly work on #18, then I will make a test case for your issue.

**Comment by AndyOGo** [comment]
@zont 
I finished automated testing and fixed some nifty bugs during this too and version `1.1.0` is out.

- Especially enabling [chokidars `awaitWriteFinish` option](https://github.com/paulmillr/chokidar#performance), fixed copying wrong paths on Linux.
- And fixed glob detection plus glob base dir resolving

May I ask you to check if this issue is resolved for you?

**Important:** please make sure to wrap your globs within `'` quotes, cause otherwise your CLI will interpret these globs and expand them, instead of letting `node-sync-glob` evaluate them itself, like:

```sh
sync-glob -w 'src/**/*.{html,json}' out
```

**Comment by zont** [comment]
Sorry, but now I use https://www.npmjs.com/package/copy-and-watch

**Comment by AndyOGo** [comment]
@zont alright, thanks for feedback though

**Comment by david-hollifield** [comment]
FWIW, I'm having this same issue using v1.3.7 of sync-glob

**Comment by AndyOGo** [comment]
@david-hollifield 
Thanks for your feedback.
May I ask you to provide platform and environment details.

If you are on windows, it has known bugs originating form `chokidar`.
Since `NSFW` is releasing I considering switching to it, see #39

**Comment by david-hollifield** [comment]
Yes, I'm on windows 10.
